N=input('请输入河流断面个数n: ');
Q1(1,1)=input('请输入背景河水流量Q0(m3/s): ');
Q=input('请输入在断面i处注入河流的污水流量Q(m3/s): ');
L=input('请输入由断面i注入河流的污水的污染物（例如BOD）浓度L(mg/L): ');
O=input('请输入由断面i注入河流的污水溶解氧（DO）浓度O(mg/L): ');
kd=input('请输入BOD的降解速度常数kd(/d): ');
ka=input('请输入大气复氧速度ka(/d): ');
t=input('请输入由断面i到断面i+1经过时间t(d): ');
Q3=input('请输入在断面i处引出的流水流量Q3(m3/s): ');
T=input('请输入河水水温/℃: ');
L20=input('请输入河流背景的BOD浓度L20(mg/L): ');
O20=input('请输入河流背景的DO浓度O20(mg/L): '); 
res=calculate(N,Q1,Q,L,O,kd,ka,t,Q3,T,L20,O20);
fprintf('U响应矩阵：\n');
disp(res{1});
fprintf('V相应矩阵：\n');
disp(res{2});
fprintf('m向量：\n');
disp(res{3});
fprintf('n向量：\n');
disp(res{4});
fprintf('各断面BOD浓度：\n');
disp(res{5});
fprintf('各断面DO浓度：\n');
disp(res{6});