run("8-bit");
setAutoThreshold("Default dark no-reset");
//run("Threshold...");
setAutoThreshold("Default dark no-reset");
run("Close");
//setThreshold(129, 255);
setOption("BlackBackground", true);
run("Convert to Mask");
run("Convert to Mask");
run("Watershed");
run("Analyze Particles...", "size=2000-Infinity show=Outlines display clear include summarize");
